AppBundle\Entity\Channel:
    type: entity
    table: channels
    repositoryClass: AppBundle\Repository\ChannelRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        status:
            type: boolean
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: update_at
    oneToMany:
        childrens:
            targetEntity: AppBundle\Entity\Channel
            mappedBy: parent
    manyToOne:
        parent:
          targetEntity: AppBundle\Entity\Channel
          inversedBy: childrens
          joinColumn:
              name: parent_id
              referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ updatedTimestamps ]
        preUpdate: [ updatedTimestamps ]
